# Generated by Django 5.0.7 on 2025-07-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryImage',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_images/'),
        ),
    ]
